spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_oauth2
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
application:
  security:
    rsa:
      rsa-public-key: classpath:certs/public-key.pem
      rsa-private-key: classpath:certs/private-key.pem
    jwt:
      access-token-validity-in-seconds: 300 # 5 minutes
      refresh-token-validity-in-seconds: 604800 #7 days