spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_oauth2
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true